[package]
authors = ["Tyler Cook"]
description = "Supporting macros for goldboot"
edition = "2021"
license = "AGPL-3.0-only"
name = "goldboot-macros"
rust-version = "1.74"
version = "0.0.1"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "2.0.39"
